export const SET_VISIBILITY_FILTER = 'Filters/types/SET_VISIBILITY_FILTER'
export const SHOW_ALL = 'Filters/types/SHOW_ALL'
export const SHOW_COMPLETED = 'Filters/types/SHOW_COMPLETED'
export const SHOW_ACTIVE = 'Filters/types/SHOW_ACTIVE'
export const SHOW_CEP = 'Filters/types/SHOW_CEP'
